## Dataset info 

name: 'hippocampus_truncated'
loom_file: '../data/hippocampus_truncated.loom' 
data_dir: 'data'
human: 0 # 1=human, 0=mouse

## Cleaning parameters

# The lower percentile of cells that will be removed, based on the unspliced matrix
cell_min_percentile: 0.004

# The minimum count each gene should have
min_expr_counts_s: 40
min_expr_counts_u: -1

# The minimum number of cells a gene should be expressed in
min_cells_express_s: 30
min_cells_express_u: -1


## UMAP parameters

# Train params
n_neighbors: 30
metric: 'correlation'
min_dist: 0.1

# Plot params
umap_color: 'ClusterName'
umap_legend: False
umap_psize: 15


## scHPF

n_factors: 15


## RNA velocity

# Main parameters
cluster_name: 'Clusters' # Column name clusters
# n_pcs: 100
k_imputation: 500

# Detail parameters
fit_offset: False
trans_prob_transform: 'sqrt'
trans_prob_nn: 500
shift_scaling: True
arrows_smooth: 0.8
arrows_steps: 70
arrows_nn: 300